apiVersion: v1
kind: PersistentVolume
metadata:
  name: trabawho-mysql-pv
  namespace: trabawho
  labels:
    app: trabawho
    component: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/trabawho-mysql
