apiVersion: v1
kind: Service
metadata:
  name: trabawho-mysql
  namespace: trabawho
  labels:
    app: trabawho
    component: mysql
spec:
  type: ClusterIP
  selector:
    app: trabawho
    component: mysql
  ports:
    - port: 3306
      targetPort: 3306
