apiVersion: v1
kind: Secret
metadata:
  name: trabawho-secret
  namespace: trabawho
type: Opaque
data:
  # base64 encoded values
  # echo -n "trabawho_pass" | base64
  DB_PASSWORD: dHJhYmF3aG9fcGFzcw==
  # echo -n "trabawho_jwt_secret_change_in_production" | base64
  JWT_SECRET: dHJhYmF3aG9fand0X3NlY3JldF9jaGFuZ2VfaW5fcHJvZHVjdGlvbg==
  # echo -n "trabawho_pass" | base64
  MYSQL_ROOT_PASSWORD: dHJhYmF3aG9fcGFzcw==
